#ifndef _CONFIG_H
#define _CONFIG_H

#define CFG_GLOBAL_BUFFER_SIZE 0x1000

#define CFG_CB_WRITE_BUFFER    4
#define CFG_CB_READ_BUFFER     CFG_GLOBAL_BUFFER_SIZE
#define CFG_CB_CONSOLE_BUFFER  CFG_GLOBAL_BUFFER_SIZE

#endif
