@ECHO OFF

IF "%1%" NEQ "x64" (
	IF "%1%" NEQ "x86" (
		ECHO Usage config.bat x64/x86
		GOTO:END
	)
)

REM #### VARS SETUP

SET "WINSDKKITVERSION=10"
SET "WINSDKVERSION=10.0.17763.0"

IF "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
	SET "WINSDKPATH=%ProgramFiles(x86)%\Windows Kits\%WINSDKKITVERSION%"
) ELSE (
	SET "WINSDKPATH=%ProgramFiles%\Windows Kits\%WINSDKKITVERSION%"
)

IF "%VS2019INSTALLDIR%" NEQ "" (
	SET "VCINSTALLDIR=%VS2019INSTALLDIR%"
) ELSE (
	SET "VCINSTALLDIR=%VS2017INSTALLDIR%"
)

FOR /F "delims=" %%A IN ('type "%VCINSTALLDIR%\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt"') DO SET "VCTOOLSVERSION=%%A"
SET "VCTOOLSPATH=%VCINSTALLDIR%\VC\Tools\MSVC\%VCTOOLSVERSION%"

IF "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
	SET "VCTOOLSBINPATH=%VCTOOLSPATH%\bin\Hostx64"
) ELSE (
	SET "VCTOOLSBINPATH=%VCTOOLSPATH%\bin\Hostx86"
)

SET "PATH=%PATH%;"
SET "WINDBGX64=%WINSDKPATH%\Debuggers\x64"
SET "WINDBGX86=%WINSDKPATH%\Debuggers\x86"
SET "WINDBG=%WINSDKPATH%\Debuggers\"

REM #### COMPILER

SET "PATH=%PATH%%VCTOOLSBINPATH%\%1%;"

IF "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
	IF "%1%" == "x86" (
		SET "PATH=%PATH%%VCTOOLSBINPATH%\x64;"
	)
)

IF "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
	IF "%1%" EQU "x64" (
		SET "PATH=%PATH%%ICPP_COMPILER19%bin\intel64;"
	) ELSE (
		SET "PATH=%PATH%%ICPP_COMPILER19%bin\intel64_ia32;"
	)
) ELSE (
	IF "%1%" EQU "x64" (
		SET "PATH=%PATH%%ICPP_COMPILER19%bin\ia32_intel64;"
	) ELSE (
		SET "PATH=%PATH%%ICPP_COMPILER19%bin\ia32;"
	)
)

SET "PATH=%PATH%%WINSDKPATH%\bin\%WINSDKVERSION%\%1%;"

REM #### INCLUDE AND LIBS

SET "PATH=%PATH%%WINSDKPATH%\bin\%WINSDKVERSION%\%1%;"
SET "PATH=%PATH%%WINSDKPATH%\Tools\%1%;"

SET "INCLUDE=%INCLUDE%%WINSDKPATH%\Include\%WINSDKVERSION%\shared;"
SET "INCLUDE=%INCLUDE%%WINSDKPATH%\Include\%WINSDKVERSION%\um;"
SET "INCLUDE=%INCLUDE%%WINSDKPATH%\Include\%WINSDKVERSION%\ucrt;"
SET "INCLUDE=%INCLUDE%%WINSDKPATH%\Include\%WINSDKVERSION%\km;"
SET "INCLUDE=%INCLUDE%%VCTOOLSPATH%\include;"
SET "INCLUDE=%INCLUDE%%ICPP_COMPILER19%compiler\include;" REM INTEL

SET "LIB=%LIB%%WINSDKPATH%\Lib\%WINSDKVERSION%\um\%1%;"
SET "LIB=%LIB%%WINSDKPATH%\Lib\%WINSDKVERSION%\ucrt\%1%;"
SET "LIB=%LIB%%WINSDKPATH%\Lib\%WINSDKVERSION%\km\%1%;"
SET "LIB=%LIB%%VCTOOLSPATH%\lib\%1%;"

IF "%1%" EQU "x64" (
	SET "LIB=%LIB%%ICPP_COMPILER19%compiler\lib\intel64_win;"
) ELSE (
	SET "LIB=%LIB%%ICPP_COMPILER19%compiler\lib\ia32_win;"
)

REM #### Utils

SET "PATH=%PATH%%WINSDKPATH%\Tools\%1%;"
SET "PATH=%PATH%%cd%\tools;"
SET "PATH=%PATH%%__GNU_MAKE%;"

SET "PROJECT_ARCH=%1%"
SET "PROJECT_PATH=%cd%"
SET "PROJECT_BIN_PATH=%PROJECT_PATH%\bin\%PROJECT_ARCH%"
SET "PROJECT_INCLUDE_PATH=%PROJECT_PATH%\source\include"

(
  "tools\build.bat" debug

  TITLE ClientTest %PROJECT_ARCH%
)

:END

